---
title: "R Notebook"
output: html_notebook
---

# Setup

```{r libraries,message=F}
library(RMySQL)
# library(dbConnect)
library(dplyr)
library(reshape2)
library(openxlsx)
library(ggplot2)
library(RJDBC)
```

```{r connection}
source('con_nautilus.R')
```

```{r info}
info<-dbGetQuery(con,"select * from INFORMATION_SCHEMA.TABLES")

info[info$TABLE_TYPE=="BASE TABLE",] %>%
  select(TABLE_NAME) %>% unique %>% c
```

# Extração de dados

```{sql connection = con, output.var = bio_ceph}
create temporary table batata(
select * from especie_generica p1
  where p1.cod_fao = 'OCC') 
select * from amostra_especie p2
  where p2.especie = batata.id
```

```{sql connection = con, output.var = caca}
select * from amostra_especie p2
 -- where  p2.especie = 'OCC'
```


```{sql connection = con, output.var = porra}
select * from bio_cefalopode p1,
              amostra_especie p2,
              caixa p3,
              denominacao p4
        where p2.especie = 'OCC'
```

```{r}
names(bio_ceph)
bio_ceph %>% filter()
```

# Compra de dados???

```{r}
compra_dados_sppfc <- dbGetQuery(con, readr::read_file('compra_dados_sppfc.sql'))
```

# Conversao pesos OCC

```{r}
lota_pesos_comp_polvos <- dbGetQuery(con, readr::read_file('lota_pesos_comp_polvos.sql'))
```

# Biológicas

```{r}
teste <- dbGetQuery(con, readr::read_file('bio_naut.sql'))
```

# Checklist

- [x] Desembarques 1986 - 2019

- [x] Biologicas 1997 - 2016

- [x] Biologicas 2017 - 2019 

- [x] Lotas - 1997 - 2016

- [x] Lotas - 2017 - 2019

- [ ] Respescar scritp dos cephs

- [ ] Procurar ampliaçõe de SOL



## Desembarques
 
```{r}
land <- read.csv("PT_land_1986_2019.csv", sep = ";")

land <- 
land %>% 
  filter(SPECIES %in% c("OCC", "OCT")) %>%
  filter(PESQUEIRO == "P") %>%
  transmute(LANDING_COUNTRY = factor(LANDING_COUNTRY),
            HARBOUR = factor(HARBOUR),
            GEAR = factor(GEAR),
            FISHING_5 = factor(FISHING_5),
            SPECIES = factor("OCC"),
            YEAR = factor(YEAR),
            MONTH = factor(MONTH),
            SUB.AREA = factor(SUB.AREA),
            land_kg = LANDINGS_WEIGHT_KG)
```       

```{r}
portos_slv <- read.csv("dados/codigos_portos.csv")
```

## Biologicas

- [ ] Verificar outliers nos comprimentos
- [ ] Uniformizar portos entre as duas tabelas

```{r bio_16}
bio16 <- read.csv("allspp_19972016_bio.csv", sep = ";", dec = ",")

bio16 <- 
bio16 %>%
  filter(COD_FAO == "OCC") %>%
  # filter()
  transmute(ID_AMOSTRA = factor(ID_AMOSTRA),
            DATA = as.POSIXct(DATA_AM, format = '%d-%m-%Y'),
            ANO = factor(ANO),
            PORTO = factor(PORTO_NOME),
            REGIAO = case_when(REGIAO == "N" ~ "27.a.c.n",
                               REGIAO == "C" ~ "27.a.c.s",
                                        TRUE ~ "27.a.s.a"),
            ARTE_EU = factor(ARTE_EU),
            COD_FAO = factor("OCC"),
            land_kg = DESEMBARQUE, # desembarque da denominação na viagem
            PESO_AM = PESO_AM,
            N_OBS = N_OBS,
            C_CLASSE = C_CLASSE,
            C_INDIVIDUAL = C_INDIVIDUAL,
            P_INDIVIDUAL = P_INDIVIDUAL,
            P_EVISCERADO = P_EVISCERADO,
            SEXO = factor(case_when(SEXO == "F" ~ "F",
                                    SEXO == "f" ~ "F",
                                    SEXO == "M" ~ "M",
                                    SEXO == "m" ~ "M",
                                    TRUE ~ "I")),
            EST_MATURACAO = factor(case_when(EST_MATURACAO == "2         " ~ "2",
                                             EST_MATURACAO == "4         " ~ "4",
                                             EST_MATURACAO == "3         " ~ "3",
                                             EST_MATURACAO == "1         " ~ "1",
                                             EST_MATURACAO == "5         " ~ "5",
                                             EST_MATURACAO == "0         " ~ "0",                                                EST_MATURACAO == "1" ~ "1",
                                             EST_MATURACAO == "2/3       " ~ "2/3",
                                             EST_MATURACAO == "" ~ "NA",
                                             EST_MATURACAO == "1       1 " ~ "1",
                                             EST_MATURACAO == "2" ~ "2",
                                             EST_MATURACAO == "3" ~ "3",
                                             EST_MATURACAO == "5" ~ "5",
                                             EST_MATURACAO == "4" ~ "4")),
            C_PENIS = C_PENIS,
            C_TEST = C_TEST,
            P_CESPERM = P_CESPERM,
            P_OVARIO = P_OVARIO,
            P_GOVID = P_GOVID,
            D_GOVID = D_GOVID,
            C_GASS = C_GASS,
            P_GASS = P_GASS,
            D_GNID = D_GNID,
            P_GNID = P_GNID,
            P_COVID = P_COVID,
            E_ESTOM = E_ESTOM,
            P_GDIGEST = P_GDIGEST,
            FECUNDADA = factor(FECUNDADA)) 

```

```{r bio19 }
bio_naut %>% group_by(ano, trim, estrategia_amostragem) %>%
  summarise(cona = length(unique(id_viagem)))

bio_naut %>%
  filter(estrategia_amostragem == "Species Focus") %>%
  transmute(id_viagem = factor(id_viagem),
            id_denominacao = factor(id_denominacao),
            id_caixa = factor(id_caixa),
            id_spp = factor(id_spp),
            id_indiv = factor(id_indiv),
            REGIAO = factor( 
              case_when(regiao == "Sul" ~ "27.9.a.s.a",
                               regiao == "SW" ~ "27.9.a.c.s",
                               regiao == "NW" ~ "27.a.c.n")),
            DATA = as.POSIXct(data_venda, format = '%Y-%m-%d'),
            trim = factor(trim),
            ANO = factor(ano),
            PORTO = factor(lota),
            land_kg = peso_total_dom,
            cat_com = factor(cat_com),
            )
  


```


